### ISSUE TITLE
Certificate expired; Userstyles can't be reached from Firefox or Chrome

### ISSUE THREAD

**Issue by hideheader** [JasonBarnabe/userstyles#100]
> The owner of userstyles.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
> 
> This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox only connect to it securely. As a result, it is not possible to add an exception for this certificate.
> 
> Learn more…
> 
> userstyles.org uses an invalid security certificate.
> 
> The certificate expired on 03/12/2016 10:17 PM. The current time is 03/12/2016 10:41 PM.
> 
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

So, you may want to rethink HSTS.

**Comment by catcat520** [comment]
same situation in china

**Comment by JasonBarnabe** [comment]
I've ordered and approved a new certificate. Just waiting for it to be issued now.

I blame the leap year and daylight savings time.

**Comment by Kezxo** [comment]
Think about using this in the future, it's free: https://letsencrypt.org/

**Comment by JasonBarnabe** [comment]
Fixed now.
