### ISSUE TITLE
'Uncaught TypeError: Cannot read property 'style' of null'

### ISSUE THREAD

**Issue by hideheader** [JasonBarnabe/userstyles#101]
Loading https://userstyles.org/styles/browse/google in Chromium 48:

Uncaught TypeError: Cannot read property 'style' of null
  switchToPanel @  [public/javascripts/stylish-install.js:160](https://github.com/JasonBarnabe/userstyles/blob/caec49dd2de7838a8b4b0ad0b8ad8e14045f0280/public/javascripts/stylish-install.js#L160)
  genericStyleCanBeInstalled @ [app/assets/javascripts/install.js:365](https://github.com/JasonBarnabe/userstyles/blob/master/app/assets/javascripts/install.js#L365)
  styleCanBeInstalledChrome @ [app/assets/javascripts/install.js:359](https://github.com/JasonBarnabe/userstyles/blob/master/app/assets/javascripts/install.js#L359)

**Comment by JasonBarnabe** [comment]
Fixed.
