### ISSUE TITLE
Can't post styles that use IDNs

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/userstyles#102]
https://github.com/JasonBarnabe/userstyles/blob/master/app/models/style.rb#L1419-L1423

Ruby's URI library doesn't handle non-ASCII. Replace with https://github.com/sporkmonger/addressable ?

**Comment by GSMITT** [comment]
+

**Comment by JasonBarnabe** [comment]
```ruby
       test 'IDN is valid URL' do
               assert Style.validate_url('http://серьёзныеигры.рф', true)
       end
```

**Comment by JasonBarnabe** [comment]
Fixed now.
