### ISSUE TITLE
Site won't detect Stylish for Safari as installed

### ISSUE THREAD

**Issue by silverwind** [JasonBarnabe/userstyles#60]
See my comments in [this issue](https://github.com/StylishThemes/GitHub-Dark/issues/204#issuecomment-69464763), which includes screenshots too. Installing through the UI works, it's just the site won't detect the extension it seems.

**Comment by JasonBarnabe** [comment]
Stylish for Safari's repo is at https://github.com/350d/stylish/; you should report it there. It's possible it's my fault, but I haven't changed anything recently.
